// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace RandomExamGenerator.DAL.Models
{
    public partial class CorrectExamResult
    {
        public int ID { get; set; }
        public int? TotalPoints { get; set; }
        public int TotalTime { get; set; }
        public DateTime ScheduledTime { get; set; }
        public double SuccessPercent { get; set; }
        public int? InstructorID { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
        public double? StudentScore { get; set; }
        public int? StudentTimeToSolve { get; set; }
        public bool? IsStudentPassed { get; set; }
    }
}
