// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; } = null!;

    [InverseProperty("Course")]
    public virtual ICollection<EnrollsIn> EnrollsIns { get; set; } = new List<EnrollsIn>();

    [InverseProperty("Course")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    [InverseProperty("Course")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Course")]
    public virtual ICollection<Teach> Teaches { get; set; } = new List<Teach>();

    [InverseProperty("Course")]
    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();
}