// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[PrimaryKey("DepartmentId", "CourseId")]
public partial class DepartmentCourse
{
    [Key]
    [Column("DepartmentID")]
    public int DepartmentId { get; set; }

    [Key]
    [Column("CourseID")]
    public int CourseId { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("DepartmentCourses")]
    public virtual Course Course { get; set; } = null!;

    [ForeignKey("DepartmentId")]
    [InverseProperty("DepartmentCourses")]
    public virtual Department Department { get; set; } = null!;
}