// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[PrimaryKey("StudentId", "CourseId")]
[Table("EnrollsIn")]
public partial class EnrollsIn
{
    [Key]
    [Column("StudentID")]
    public int StudentId { get; set; }

    [Key]
    [Column("CourseID")]
    public int CourseId { get; set; }

    public bool CourseActive { get; set; }

    public DateOnly EnrollDate { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public bool? IsPassed { get; set; }

    public bool? IsCorrective { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("EnrollsIns")]
    public virtual Course Course { get; set; } = null!;

    [ForeignKey("StudentId")]
    [InverseProperty("EnrollsIns")]
    public virtual Student Student { get; set; } = null!;
}