// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("Exam")]
public partial class Exam
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int? TotalPoints { get; set; }

    /// <summary>
    /// Represents the duration of the exam in seconds.
    /// </summary>
    public int TotalTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ScheduledTime { get; set; }

    public double SuccessPercent { get; set; }

    [Column("InstructorID")]
    public int? InstructorId { get; set; }

    [Column("CourseID")]
    public int CourseId { get; set; }

    [Column("StudentID")]
    public int StudentId { get; set; }

    public double? StudentScore { get; set; }

    /// <summary>
    /// Represents the time the student took to solve the exam in seconds.
    /// </summary>
    public int? StudentTimeToSolve { get; set; }

    public bool? IsStudentPassed { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [ForeignKey("CourseId")]
    [InverseProperty("Exams")]
    public virtual Course Course { get; set; } = null!;

    [InverseProperty("Exam")]
    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    [ForeignKey("InstructorId")]
    [InverseProperty("Exams")]
    public virtual Instructor? Instructor { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("Exams")]
    public virtual Student Student { get; set; } = null!;
}