// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace RandomExamGenerator.DAL.Models
{
    public partial class GetChoicesForQuestionResult
    {
        public int QuestionID { get; set; }
        public int OrderInQuestion { get; set; }
        public string Body { get; set; } = default!;
        public bool IsAnswer { get; set; }
    }
}
