// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace RandomExamGenerator.DAL.Models
{
    public partial class GetStudentAnswerInExamResult
    {
        public int StudentID { get; set; }
        public int ExamID { get; set; }
        public int QuestionID { get; set; }
        public int ModelAnswer { get; set; }
        public int StudentAnswer { get; set; }
        public int Grade { get; set; }
    }
}
