// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace RandomExamGenerator.DAL.Models
{
    public partial class GetStudentCoursesResult
    {
        public string Name { get; set; } = default!;
        public string Gender { get; set; } = default!;
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public bool CourseActive { get; set; }
        public DateOnly EnrollDate { get; set; }
        public DateOnly StartDate { get; set; }
        public DateOnly EndDate { get; set; }
        public bool? IsPassed { get; set; }
        public bool? IsCorrective { get; set; }
    }
}
