// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("InstructorRole")]
public partial class InstructorRole
{
    [Key]
    [Column("InstructorRoleID")]
    [StringLength(20)]
    public string InstructorRoleId { get; set; } = null!;

    [InverseProperty("RoleNavigation")]
    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();
}