// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("Question")]
public partial class Question
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(20)]
    public string Type { get; set; } = null!;

    /// <summary>
    /// Represents OrderInQuestion for the choice marked as the answer for this (Single Choice,T/F) Question
    /// </summary>
    public int ModelAnswer { get; set; }

    [StringLength(20)]
    public string Difficulty { get; set; } = null!;

    [StringLength(1000)]
    public string Header { get; set; } = null!;

    [Column("CourseID")]
    public int CourseId { get; set; }

    public int Points { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [InverseProperty("Question")]
    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    [ForeignKey("CourseId")]
    [InverseProperty("Questions")]
    public virtual Course Course { get; set; } = null!;

    [ForeignKey("Difficulty")]
    [InverseProperty("Questions")]
    public virtual QuestionDifficulty DifficultyNavigation { get; set; } = null!;

    [InverseProperty("Question")]
    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    [InverseProperty("Question")]
    public virtual ICollection<TopicQuestion> TopicQuestions { get; set; } = new List<TopicQuestion>();

    [ForeignKey("Type")]
    [InverseProperty("Questions")]
    public virtual QuestionType TypeNavigation { get; set; } = null!;
}