// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("QuestionType")]
public partial class QuestionType
{
    [Key]
    [Column("QuestionTypeID")]
    [StringLength(20)]
    public string QuestionTypeId { get; set; } = null!;

    [InverseProperty("TypeNavigation")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}