// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace RandomExamGenerator.DAL.Models
{
    public partial class ReadTopicResult
    {
        [Column("Topic Name")]
        public string TopicName { get; set; } = default!;
        [Column("Topic ID")]
        public int TopicID { get; set; }
        [Column("Course Name")]
        public string CourseName { get; set; } = default!;
    }
}
