// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace RandomExamGenerator.DAL.Models
{
    public partial class SelectTopicResult
    {
        public int ID { get; set; }
        public int CourseID { get; set; }
        public string Name { get; set; } = default!;
    }
}
