// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace RandomExamGenerator.DAL.Models
{
    public partial class SP_GetCoursesByInstructorResult
    {
        public string CourseName { get; set; } = default!;
        public int? NumberStudents { get; set; }
    }
}
