// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace RandomExamGenerator.DAL.Models
{
    public partial class SP_GetStudentGradesResult
    {
        public double? Grade { get; set; }
        public double SuccessPercent { get; set; }
        public string Name { get; set; } = default!;
    }
}
