// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Keyless]
[Table("TaughtIn")]
public partial class TaughtIn
{
    [Column("CourseID")]
    public int CourseId { get; set; }

    [Column("TrackID")]
    public int TrackId { get; set; }

    [ForeignKey("CourseId")]
    public virtual Course Course { get; set; } = null!;

    [ForeignKey("TrackId")]
    public virtual Track Track { get; set; } = null!;
}