// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[PrimaryKey("CourseId", "InstructorId")]
public partial class Teach
{
    [Key]
    [Column("CourseID")]
    public int CourseId { get; set; }

    [Key]
    [Column("InstructorID")]
    public int InstructorId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Teaches")]
    public virtual Course Course { get; set; } = null!;

    [ForeignKey("InstructorId")]
    [InverseProperty("Teaches")]
    public virtual Instructor Instructor { get; set; } = null!;
}