// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[PrimaryKey("TopicId", "QuestionId")]
public partial class TopicQuestion
{
    [Key]
    [Column("TopicID")]
    public int TopicId { get; set; }

    [Key]
    [Column("QuestionID")]
    public int QuestionId { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("TopicQuestions")]
    public virtual Question Question { get; set; } = null!;

    [ForeignKey("TopicId")]
    [InverseProperty("TopicQuestions")]
    public virtual Topic Topic { get; set; } = null!;
}