// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("Topic")]
public partial class Topic
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("CourseID")]
    public int CourseId { get; set; }

    [StringLength(100)]
    public string Name { get; set; } = null!;

    [ForeignKey("CourseId")]
    [InverseProperty("Topics")]
    public virtual Course Course { get; set; } = null!;

    [InverseProperty("Topic")]
    public virtual ICollection<TopicQuestion> TopicQuestions { get; set; } = new List<TopicQuestion>();
}