// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("Track")]
public partial class Track
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(100)]
    public string Name { get; set; } = null!;

    [Column("DepartmentID")]
    public int DepartmentId { get; set; }

    public int? InstructorSupervisor { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Tracks")]
    public virtual Department Department { get; set; } = null!;

    [ForeignKey("InstructorSupervisor")]
    [InverseProperty("Tracks")]
    public virtual Instructor? InstructorSupervisorNavigation { get; set; }
}