// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("UserAccount")]
[Index("UserName", Name = "UQ_UserAccount_UserName", IsUnique = true)]
public partial class UserAccount
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(64)]
    public string PasswordHash { get; set; } = null!;

    [StringLength(20)]
    public string Type { get; set; } = null!;

    [StringLength(100)]
    public string UserName { get; set; } = null!;

    [InverseProperty("IdNavigation")]
    public virtual Instructor? Instructor { get; set; }

    [ForeignKey("Type")]
    [InverseProperty("UserAccounts")]
    public virtual UserAccountType TypeNavigation { get; set; } = null!;
}