// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RandomExamGenerator.DAL.Models;

[Table("UserAccountType")]
public partial class UserAccountType
{
    [Key]
    [Column("UserAccountTypeID")]
    [StringLength(20)]
    public string UserAccountTypeId { get; set; } = null!;

    [InverseProperty("TypeNavigation")]
    public virtual ICollection<UserAccount> UserAccounts { get; set; } = new List<UserAccount>();
}